### ISSUE TITLE
Building on Stable

### ISSUE THREAD

**Issue by zrneely** [Munksgaard/session-types#29]
Is there any progress or desire for progress towards getting this library to build on the stable branch? Or is there no way around use of the mpsc select feature?

**Comment by laumann** [comment]
There is little/no progress, because we figured that eventually mpsc select will become stable.

Getting rid of mpsc select either requires implementing `Select` functionality from scratch, or removing it entirely - neither option is very attractive. Although, from https://github.com/rust-lang/rust/blob/stable/src/libstd/sync/mpsc/select.rs, it doesn't seem like `Select` depends on unstable features...

One solution could be to maintain a separate branch of session types that builds on stable, would that work for you?

**Comment by zrneely** [comment]
I'm not suggesting that you maintain a whole separate branch (!) - I can make a local copy/fork without the `Select` functionality (which I don't use). I was just wondering what the plans are regarding this, especially since I've had a hard time finding an RFC or issue regarding the `mpsc_select` feature on the main rust repo.

**Comment by laumann** [comment]
Ah ok - yeah, the `mpsc_select` feature has been unstable for a while (as long as I've worked with Rust, at least), and there doesn't really seem to be any progress towards stabilizing it.

The short answer is: We'd be interested in having session-types build on stable, but it doesn't have high priority.

**Comment by mbudde** [comment]
The tracking issue for `mpsc_select` is [#27800](https://github.com/rust-lang/rust/issues/27800).

Have you considered using Cargo ["features"](http://doc.crates.io/manifest.html#the-features-section) to make the select feature optional?

**Comment by Munksgaard** [comment]
> Have you considered using Cargo "features" to make the select feature optional?

That sounds like a good compromise while we wait for stabilization :smile:
