### ISSUE TITLE
mpsc is being deprecated/removed

### ISSUE THREAD

**Issue by Munksgaard** [Munksgaard/session-types#45]
See the discussion here: https://github.com/rust-lang/rust/issues/27800#issuecomment-421760863

We should look into whether or not we can use [crossbeam channels](https://github.com/crossbeam-rs/crossbeam-channel) instead, since they seem to be the replacement of choice. Other options may be viable as well. That'll also help us actually have something useful that works on stable.

**Comment by stjepang** [comment]
Hi, author of `crossbeam-channel` here.

It looks like you're using `std::sync::mpsc::Select` in a specific manner where you wait for a `Receiver` to become ready, but then you don't follow up with a receive operation.

In `crossbeam-channel`, `Select` waits for an operation to become ready, but then you **must** follow up and complete it. See [here](https://docs.rs/crossbeam-channel/0.3.0/crossbeam_channel/struct.Select.html#method.select). That sounds like it might be a problem for your use case.

I'm considering adding a similar method `fn wait(&mut self) -> usize` that waits until an operation becomes ready, but you don't have to follow through. The `wait` method would also have counterparts `try_wait` and `wait_timeout`.

What do you think? I'm accepting feature requests. :)

**Comment by laumann** [comment]
@stjepang Thanks for weighing in!

You are correct. We assemble a list of of channels that can allows to call either `.recv()` or `.offer()` and return the index (by default) of the channel in the list who can progress. However, the indicated channel can _only_ be allowed to call either `.recv()` or `.offer()` - this is ensured by the types.

But I'd like better to understand the requirements on completion. From [this example](https://docs.rs/crossbeam-channel/0.3.0/crossbeam_channel/struct.SelectedOperation.html#examples-2):

```
use crossbeam_channel::{bounded, Select, RecvError};

let (s, r) = bounded::<i32>(0);
drop(s);

let mut sel = Select::new();
let oper1 = sel.recv(&r);

let oper = sel.select();
assert_eq!(oper.index(), oper1);
assert_eq!(oper.recv(&r), Err(RecvError));
```
Would it be incorrect to extract `oper.index()`, drop `sel`, `oper1` and `oper` and just call `r.recv()` ?

**Comment by laumann** [comment]
> I'm considering adding a similar method `fn wait(&mut self) -> usize` that waits until an operation becomes ready, but you don't have to follow through. The `wait` method would also have counterparts `try_wait` and `wait_timeout`.

For our use case, instead of `fn wait(&mut self) -> usize` make it `fn wait(self) -> usize`, such that finding the index of the ready channel consumes the `Select`. We mostly only need it for implementing the `chan_select!` macro.

I built the `ChanSelect` such that users could choose value types to return when calling `wait()`. But I only wanted `wait()` to identify the channel that was ready, and not force anything beyond that. For `chan_select!` the type is `usize` which is then index of the channel in the internal list.

**Comment by stjepang** [comment]
> Would it be incorrect to extract `oper.index()`, drop `sel`, `oper1` and `oper` and just call `r.recv()` ?

Yes, that would be incorrect.

Note that `.select()` returns a `SelectedOperation<'_>`, which implies that a slot in the channel has been reserved. Then you need to do one of the following two things:

* Call `oper.recv(...)`, which will take the message from the slot and unreserve it.
* Call `oper.send(...)`, which will put a message into the slot and complete the operation.

> EDIT: Ah, I just spotted the [`Drop` implementation](https://docs.rs/crossbeam-channel/0.3.0/src/crossbeam_channel/select.rs.html#809-812) smile But we could work around that with `mem::forget()`, I guess.

If you do nothing, dropping `SelectedOperation<'_>` will panic because reserving a slot and not following through is really bad and might cause deadlocks down the line. Don't `mem::forget()` it! :)

> For our use case, instead of `fn wait(&mut self) -> usize` make it `fn wait(self) -> usize`, such that finding the index of the ready channel consumes the `Select`

Well, you could do `{sel}.select()`, which will drop `sel` right after `.select()` finishes.

The reason why I suggest taking a `&mut self` is so that an instance of `Select` can be reused across multiple selections. For example, if you need to select multiple times in a loop, that means you don't have to rebuild the list of operations every time, which means better performance.

**Comment by laumann** [comment]
> The reason why I suggest taking a `&mut self` is so that an instance of Select can be reused across multiple selections. For example, if you need to select multiple times in a loop, that means you don't have to rebuild the list of operations every time, which means better performance.

That makes sense, but doesn't really play well with the way we use the type system to enforce adherence to the protocol. Say, the next "step" in a channel is `Recv`, then its type will be something like:

```
Chan<Recv<P>, E>
```

where `P` is the subsequent protocol to execute. Only when the type is `Chan<Recv<P>, E>` do we allow the `.recv()` method to be called, and after that its type should become

```
Chan<P, E>
```
Ie, it should be possible to call `recv()` more than once for the same "step" in the protocol: This means `recv()` must consume the channel (to return a channel with the new type).

This is also why we cannot have the `Select` still alive when calling `.recv()` - otherwise we wouldn't be allowed to move the `Chan` (because it's still referenced in the `Select`).

Although, the simple solution would then be to manually drop the `Select` after calling `.wait()` as you suggest, then everything should just work, I think.

**Comment by stjepang** [comment]
Thanks for elaborating, @laumann!

That sounds interesting, I should really go and read your paper now. :)

> Although, the simple solution would then be to manually drop the `Select` after calling `.wait()` as you suggest, then everything should just work, I think.

Yep, that will work. `&mut self` is here just to make things faster when possible, and it's easy enough to simulate `self` by manually dropping the `Select`.

**Comment by laumann** [comment]
> That sounds interesting, I should really go read your paper now. :)

It's only [10 pages](http://munksgaard.me/papers/laumann-munksgaard-larsen.pdf)! What are you waiting for :stuck_out_tongue:  

I think it's a fun use of move semantics, because implementing session types requires affine types to enforce that protocol steps are not repeated. Which is exactly what move semantics are!

For example, to send a value (I've removed the [enviroment `E`]( https://github.com/Munksgaard/session-types/blob/master/src/lib.rs#L218-L228) here):
```
impl<P, A: marker::Send + 'static> Chan<Send<A, P>> {
    pub fn send(self, v: A) -> Chan<P> {
        unsafe {
            write_chan(&self, v);
            transmute(self)
        }
    }
}
```
 - The protocol "step" is `Send<A, P>`, which means "send value of type `A`, then continue with `P`"
 - `send()` consumes the channel, and returns `Chan<P>`, which is the continuation of the protocol.

So the trick is we model all protocol steps with individual `impl` blocks that only allow methods to exist when the protocol allows it.
